# Generated by Django 3.1.1 on 2020-09-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
