# Generated by Django 3.1.1 on 2020-09-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0003_auto_20200924_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
